### ISSUE TITLE
unknown error, please try again / ImportError: no module named 'Crypto'

### ISSUE THREAD

**Issue by chen-zehua** [Yufeikang/bcloud#32]
安装之后无法登录，登录GUI提示：  
```
unknown error, please try again
```  
从shell启动提示如下错误：  
```
2017-06-15 11:21:49,970 util.py :23 ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bcloud/util.py", line 20, in <module>
    from Crypto.PublicKey import RSA
ImportError: No module named 'Crypto'

2017-06-15 11:21:49,971 gutil.py :34 WARNING Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bcloud/gutil.py", line 24, in <module>
    import keyring
ImportError: No module named 'keyring'

2017-06-15 11:22:03,878 SigninDialog.py :365 ERROR SigninDialog.on_post_login: (9, None), None

```

**Comment by chen-zehua** [comment]
补充：
我已经使用
```
pip3 install Crypto
```
安装了Crypto
仍然有以上错误

**Comment by Yufeikang** [comment]
ImportError: No module named 'keyring'

**Comment by chen-zehua** [comment]
我使用
```
pip3 install keyring
```
安装了`keyring`之后，不会报`ImportError: No module named 'keyring' `的错误了，
但是仍然有`ImportError: No module named 'Crypto'`的错误

后来发现，使用
```
pip3 install Crypto
```
安装的**Crypto**所在目录首字母是小写**crypto**
所以，我把`/path/to/bcloud/util.py`中的**Crypto**改为了**crypto**
发现新的错误
```
ImportError: No module named 'crypto.PublicKey'
```
不知道如何解决

**Comment by Yufeikang** [comment]
抱歉，刚刚在另一台机器上测试了一下，确实是这个问题，查了一下。依赖的是这个模块 
`sudo pip3 install pycrypto `

**Comment by chen-zehua** [comment]
**问题已解决**
谢谢！
我在已关闭的issue看到了相同的问题，有解决方案。
