### ISSUE TITLE
在fedora 25的virtualenv中安装，启动时报错

### ISSUE THREAD

**Issue by samsong8610** [Yufeikang/bcloud#33]
环境：
```
$ uname -a
Linux sam-pc.local 4.11.3-200.fc25.x86_64 #1 SMP Thu May 25 19:03:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ virtualenv --version
15.1.0
$ $ python -V
Python 3.5.3
$ pip list installed
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
bcloud (3.9.0)
certifi (2017.4.17)
chardet (3.0.4)
gi (1.2)
idna (2.5)
pip (9.0.1)
requests (2.18.1)
setuptools (36.0.1)
urllib3 (1.21.1)
wheel (0.29.0)
```
重现步骤：
```
$ virtualenv -p python3 .venv
$ source .venv/bin/activate
(.venv) $ python setup.py install
(.venv) $ ./bcloud-gui
Traceback (most recent call last):
  File "./bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/home/sam/opt/bcloud/bcloud/App.py", line 10, in <module>
    import gi
ImportError: No module named 'gi'
(.venv) $ pip install gi
(.venv) $ ./bcloud-gui 
Traceback (most recent call last):
  File "./bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/home/sam/opt/bcloud/bcloud/App.py", line 10, in <module>
    import gi
  File "/home/sam/opt/bcloud/.venv/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```
这个问题是gi包不支持python3导致，手工修改报错代码为print(url)，41行也做相似修改。
```
(.venv) [sam@sam-pc bcloud]$ ./bcloud-gui 
Traceback (most recent call last):
  File "./bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/home/sam/opt/bcloud/bcloud/App.py", line 12, in <module>
    gi.require_version('Gdk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'
```
检查了python2.7下的gi，也是没有`require_version`方法的。
能不能在代码中提供一个`requirements.txt`，可以通过`pip install -r requirements.txt`一次性安装好所有依赖？

**Comment by Yufeikang** [comment]
好的，有时间搞一下，最近太忙
