### ISSUE TITLE
Debian9.0安装后无法启动

### ISSUE THREAD

**Issue by sulydee** [Yufeikang/bcloud#37]
操作系统：Debian9.0
桌面：Cinnamon
问题：安装后在菜单里点击bcloud无法启动

在终端执行（加sudo也一样）：
$ bcloud-gui
```
Traceback (most recent call last):
  File "/usr/local/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/local/lib/python3.5/dist-packages/bcloud/App.py", line 30, in <module>
    from bcloud import gutil
  File "/usr/local/lib/python3.5/dist-packages/bcloud/gutil.py", line 20, in <module>
    from bcloud import pcs
  File "/usr/local/lib/python3.5/dist-packages/bcloud/pcs.py", line 13, in <module>
    from lxml import html
ImportError: No module named 'lxml'

```

**Comment by Yufeikang** [comment]
sudo pip3 install lxml

**Comment by sulydee** [comment]
可以了，谢谢作者大神！
启发：
根据错误的输出结果，查看缺失的文件，使用命令：
`$ sudo pip3 install package`
安装缺失的包即可！
再次感谢@Yufeikang ！
