### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by ruichangliang** [Yufeikang/bcloud#45]
manjaro17.0.2 运行时报错
Traceback (most recent call last):
  File "./bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/home/liang/下载/bcloud-master/bcloud/App.py", line 50, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

**Comment by ManiaciaChao** [comment]
装好 appindicator3 应该就可以。
sudo apt install gir1.2-appindicator3-0.1

**Comment by jinjiachen** [comment]
解决了，成功运行，再次感谢

**Comment by windilt** [comment]
opensuse需要安装 typelib-1_0-AppIndicator3-0_1

**Comment by askerlee** [comment]
@ManiaciaChao 我的ubuntu需要装
`sudo apt-get install libappindicator3-dev`
