### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by bee-ng** [Yufeikang/bcloud#46]
kali rolling 运行错误
Traceback (most recent call last):
  File "/usr/local/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/local/lib/python3.5/dist-packages/bcloud/App.py", line 21, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available

**Comment by Yoo-4x** [comment]
目测是有包没有装，请在最早的那个库里找 依赖包
