### ISSUE TITLE
您好，首先感谢你的付出，这是我第一次在git上给人回复，哈哈

### ISSUE THREAD

**Issue by xieyabo1993** [Yufeikang/bcloud#48]
这里是我遇到的一个问题：
Ubuntu16.04   64位

你说的Python3包我都装过了，点击图标无法启动
sudo bcloud-gui启动，出现如下错误：

2017-07-28 19:33:31,347 SigninDialog.py :97 ERROR SigninVcode.refresh_vcode: None, Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bcloud/gutil.py", line 115, in do_call
    result = func(*args)
  File "/usr/local/lib/python3.5/dist-packages/bcloud/auth.py", line 170, in refresh_signin_vcode
    '&vcodetype=', encoder.encode_uri(vcodetype),
TypeError: sequence item 3: expected str instance, dict found

**Comment by Yufeikang** [comment]
估计是百度最近又改什么协议了，我这几天看看什么问题，请关注更新

**Comment by Yufeikang** [comment]
@xieyabo1993 你应该是第一次用这个客户端吧，目前不支持百度的两步验证，新设备登陆百度要求验证手机或者邮箱导致的无法登陆。多在浏览器用几天再试吧
