### ISSUE TITLE
 The handshake operation timed out

### ISSUE THREAD

**Issue by Yoo-4x** [Yufeikang/bcloud#51]
下载途中出现 urllib.error.URLError: <urlopen error _ssl.c:733: The handshake operation timed out>错误
之后点击继续下载按钮能够继续下载，请问这个是软件问题还是缺少安装包？

**Comment by Yoo-4x** [comment]
2017-08-17 03:46:17,202 Downloader.py :66 DEBUG DownloadBatch.get_req: 270053245, 308632284
2017-08-17 03:46:27,644 Downloader.py :78 ERROR Traceback (most recent call last):
  File "/usr/lib64/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))     
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)    
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)                                          
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()                                          
  File "/usr/lib64/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)                        
  File "/usr/lib64/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)                        
  File "/usr/lib64/python3.6/ssl.py", line 808, in __init__ 
    self.do_handshake()                                     
  File "/usr/lib64/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()                             
  File "/usr/lib64/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()                             
socket.timeout: _ssl.c:733: The handshake operation timed out
Traceback (most recent call last):                         
  File "/usr/lib64/python3.6/site-packages/bcloud/Downloader.py", line 76, in get_req
    return opener.open(self.url, timeout=self.timeout)     
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)                         
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)            
  File "/usr/lib64/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)                       
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)                                   
  File "/usr/lib64/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)      
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)                       
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)                                          
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)                                   
  File "/usr/lib64/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)                                    
urllib.error.URLError: <urlopen error _ssl.c:733: The handshake operation timed out>
