### ISSUE TITLE
bcloud-gui中要导入的html模块装不上

### ISSUE THREAD

**Issue by Zangwill** [Yufeikang/bcloud#53]
之前运行挺好的，可能不知道装错了什么，打不开了，终端里运行`bcloud-gui`，显示没`html`，但是我用`pip3 install html`装不上这个，一直显示`AttributeError: 'str' object has no attribute 'decode' 。`有什么解决办法吗？
```bash
$ bcloud-gui 
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3.6/site-packages/bcloud/App.py", line 30, in <module>
    from bcloud import gutil
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 20, in <module>
    from bcloud import pcs
  File "/usr/lib/python3.6/site-packages/bcloud/pcs.py", line 13, in <module>
    from lxml import html
ImportError: cannot import name 'html'
```
```bash
# pip3 install html
Collecting html                      
  Using cached html-1.16.tar.gz      
    Complete output from command python setup.py egg_info:                 
    Traceback (most recent call last):                                     
      File "<string>", line 1, in <module>                                 
      File "/tmp/pip-build-vdo60zix/html/setup.py", line 12, in <module>   
        long_description = __doc__.decode('utf8'),                         
    AttributeError: 'str' object has no attribute 'decode'                 
                                     
    ----------------------------------------                               
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vdo60zix/html/
```

**Comment by poplite** [comment]
用 pip3 install lxml

**Comment by Zangwill** [comment]
@poplite ,谢谢，问题解决了，就是用`pip3 install lxml`显示已经装了，卸了之后用`pip3 --no-cache-dir install lxml`重新装才好
