### ISSUE TITLE
运行bcloud报错

### ISSUE THREAD

**Issue by kloongin** [Yufeikang/bcloud#54]
Traceback (most recent call last):   File "/usr/local/bin/bcloud-gui", line 11, in <module>     from bcloud.App import App   File "/usr/local/lib/python3.6/site-packages/bcloud/App.py", line 10, in <module>     import gi ModuleNotFoundError: No module named 'gi'

**Comment by Yufeikang** [comment]
缺少依赖，gi

**Comment by liufitch** [comment]
我也是这个。。依赖怎么添加？？

**Comment by poplite** [comment]
sudo apt-get install python3-gi
