### ISSUE TITLE
archlinux 缺少dbus

### ISSUE THREAD

**Issue by jinjiachen** [Yufeikang/bcloud#56]
运行bcloud后出现如下错误：
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3.6/site-packages/bcloud/App.py", line 30, in <module>
    from bcloud import gutil
  File "/usr/lib/python3.6/site-packages/bcloud/gutil.py", line 12, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

于是查找了下这个依赖，发现是安装了的，如下：
extra/python-dbus 1.2.4-2
extra/python-dbus-common 1.2.4-2 [已安装]
    Common dbus-python files shared between python-dbus and python2-dbus
extra/python2-dbus 1.2.4-2 [已安装]
community/python-secretstorage 2.3.1-3
community/python2-secretstorage 2.3.1-3

请问该如何解决？

**Comment by poplite** [comment]
bcloud运行于python3，请安装python3版本的依赖包。

**Comment by jinjiachen** [comment]
谢谢你的回复，我已经安装了相关依赖，并且安装了kering,最后出现的提示并不是缺少依赖包，错误如下：
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3.6/site-packages/bcloud/App.py", line 50, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

这个有点没头绪了

**Comment by poplite** [comment]
试试#45
