### ISSUE TITLE
ImportError: cssselect does not seem to be installed

### ISSUE THREAD

**Issue by liufitch** [Yufeikang/bcloud#57]
Traceback (most recent call last):
  File "./bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/home/fitch/Downloads/bcloud/bcloud/App.py", line 23, in <module>
    from bcloud import gutil
  File "/home/fitch/Downloads/bcloud/bcloud/gutil.py", line 21, in <module>
    from bcloud import pcs
  File "/home/fitch/Downloads/bcloud/bcloud/pcs.py", line 15, in <module>
    from lxml.cssselect import CSSSelector as CSS
  File "/usr/lib/python3/dist-packages/lxml/cssselect.py", line 16, in <module>
    'cssselect does not seem to be installed. '
ImportError: cssselect does not seem to be installed. See http://packages.python.org/cssselect/

出现这个问题..
 sudo pip install cssselect  -->Successfully installed cssselect-1.0.1-->still 出现这个问题

**Comment by poplite** [comment]
用`sudo pip3 install cssselect `安装python3版本的cssselect。

**Comment by liufitch** [comment]
Traceback (most recent call last):
  File "./bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/home/fitch/Downloads/bcloud/bcloud/App.py", line 37, in <module>
    from bcloud.FileWatcher import WatchFileChange
  File "/home/fitch/Downloads/bcloud/bcloud/FileWatcher.py", line 8, in <module>
    import pyinotify
ImportError: No module named 'pyinotify'
又出现这个问题..

**Comment by poplite** [comment]
https://github.com/LiuLang/bcloud-packages/blob/master/build_deb/control 这是Liulang原版deb包的依赖，可以参考一下。

**Comment by liufitch** [comment]
这些可以用dpkg装吗?我不懂python

**Comment by poplite** [comment]
可以，用`sudo apt-get install + 依赖包名称`。
在Ubuntu下安装python3库有两种方式(以cssselect为例)
`sudo apt-get install python3-cssselect`
`sudo pip3 install cssselect`(要先安装python-pip3包)

**Comment by liufitch** [comment]
好的 万分感谢 我试一试

**Comment by liufitch** [comment]
run ./bcloud-gui and 
show
/home/fitch/Downloads/bcloud/bcloud/App.py:11: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gdk
/home/fitch/Downloads/bcloud/bcloud/App.py:15: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/home/fitch/Downloads/bcloud/bcloud/App.py:16: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/home/fitch/Downloads/bcloud/bcloud/App.py:41: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as AppIndicator

i logged in but  it occured error:"unknown error ,please try again". im sure that username and password are correct.  and i dont know how to fix it

**Comment by poplite** [comment]
Log出现的警告不影响使用，但应该已经修复了(3b08c30)。你用的是不是旧版本?

**Comment by liufitch** [comment]
mine is bcloud-3.8.2.tar.gz

**Comment by poplite** [comment]
You are using a deprecated version.bcloud is no longer maintained by @Liulang, its original author since 3.8.2.@Yufeikang fixed many bugs and released newer version of bcloud.You should download the lastest version.

**Comment by liufitch** [comment]
我换成 3.9.1之后 出现
2017-10-01 06:56:37,538 ERROR Traceback (most recent call last):
  File "/home/fitch/Downloads/bcloud-3.9.1/bcloud/util.py", line 20, in <module>
    from Crypto.PublicKey import RSA
ImportError: No module named 'Crypto'

/home/fitch/Downloads/bcloud-3.9.1/bcloud/App.py:45: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3 as AppIndicator
2017-10-01 06:57:27,765 ERROR SigninDialog.on_post_login: (9, None), None
 可是 我运行了sudo pip3 install Crypto
还是不行，仍然出现ImportError: No module named 'Crypto'

**Comment by poplite** [comment]
#14 请先看一看先前的Issue再提问。。。

**Comment by liufitch** [comment]
好的 已经解决 万分感谢 。。
