### ISSUE TITLE
运行报错, 缺少cssselect包

### ISSUE THREAD

**Issue by zhzdeng** [Yufeikang/bcloud#60]
```
deng@deng-PC:~/software/bcloud$ bcloud-gui &
[1] 4895
deng@deng-PC:~/software/bcloud$ Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lxml/cssselect.py", line 13, in <module>
    import cssselect as external_cssselect
ImportError: No module named 'cssselect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/local/lib/python3.5/dist-packages/bcloud/App.py", line 30, in <module>
    from bcloud import gutil
  File "/usr/local/lib/python3.5/dist-packages/bcloud/gutil.py", line 20, in <module>
    from bcloud import pcs
  File "/usr/local/lib/python3.5/dist-packages/bcloud/pcs.py", line 14, in <module>
    from lxml.cssselect import CSSSelector as CSS
  File "/usr/lib/python3/dist-packages/lxml/cssselect.py", line 16, in <module>
    'cssselect does not seem to be installed. '
ImportError: cssselect does not seem to be installed. See http://packages.python.org/cssselect/
```
问题我自己解决了,特地来提醒作者把cssselect加入到requiements.txt

**Comment by huimin123** [comment]
我安装cssselect包显示成功了，但还是报错，想问一下你是怎么解决的

**Comment by zhzdeng** [comment]
@huimin123 
用下面命令安装 cssselect 就运行成功了 
```
pip3 install cssselect --user
```
