### ISSUE TITLE
Can not download file

### ISSUE THREAD

**Issue by xuleilx** [Yufeikang/bcloud#68]
2018-03-18 22:40:26,033 net.py :70 ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/bcloud/net.py", line 68, in urlopen_simple
    return urllib.request.urlopen(url, timeout=timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

2018-03-18 22:40:26,034 Downloader.py :196 WARNING Failed to get url to download

**Comment by yufeikang** [comment]
这个项目已经很久没有维护。请关注baidupcs https://github.com/GangZhuo/BaiduPCS  不错

**Comment by xuleilx** [comment]
已经关注，在用了。
