### ISSUE TITLE
登录之后，弹出Network error

### ISSUE THREAD

**Issue by yfcube** [Yufeikang/bcloud#69]
`2018-07-02 11:18:14,027 net.py :126 ERROR Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/bcloud/net.py", line 117, in urlopen
    req = opener.open(url, data=data, timeout=timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1210, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1185, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1208, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 380, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 342, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer`

**Comment by yufeikang** [comment]
这个项目不再维护，用这个吧 https://github.com/iikira/BaiduPCS-Go
